scenario_type: two_phase
meteorology:
  wind_speed: 3.9
  z_ref: 3.0
  z0: 0.0004
  stability_class: D
source:
  hole_diameter_m: 0.06
  discharge_coeff: 0.6
  duration_s: 3600
chemical:
  name: Ammonia
  MW_g_mol: 17.03
